abstract: OO dispatching and inheritance for templates
author: Sam Vilain <samv@cpan.org>
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: perl
name: Template-Plugin-Heritable
no_index: 
  directory: 
    - inc
    - t
recommends: 
  MRO::Compat: 0
  Moose: 0
requires: 
  Template: 2
  perl: 5.005
version: 0.03
