abstract: OO dispatching and inheritance for templates
author: Sam Vilain <samv@cpan.org>
build_requires: 
  Test::Depends: 0.02
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.61
license: perl
name: Template-Plugin-Heritable
no_index: 
  directory: 
    - inc
    - t
recommends: 
  T2: 0.1
requires: 
  Template: 2
  perl: 5.005
version: 0.02
