name: Template-Plugin-Heritable
version: 0.01
abstract: OO dispatching and inheritance for templates
author: Sam Vilain <samv@cpan.org>
license: perl
distribution_type: module
build_requires:
  Test::More: 0
  Test::Depends: 0
requires:
  perl: 5.005
  Template: 2
recommends:
  T2: 0.1
no_index:
  directory:
    - inc
generated_by: Module::Install version 0.39
